### PR TITLE
Add (opinionated) nix flake build

### PR DESCRIPTION
**Pull request by Anderssorby**
I wanted to add a nix flake setup which is my opinionated setup, but resembles a lot of other languages' structure. It makes compilation and dependency management very plug and play although more work is needed.

### CODE REVIEW

**Comment by lecopivo** [comment]
I have no clue what nix is good for :) What is this giving me? I feel that this project is in such an early and experimental stage that adding another way how to build it apart from just using `lake build` is the last thing we should worry about right now. On the other hand, I'm happy to be convinced of the opposite.

**Comment by Anderssorby** [comment]
@lecopivo Well, if you are using a unix system nix provides a really nice and deterministic plug and play development environment. I use it for all my projects because it means I can build any project with zero configurations and the same result every time which is super nice when sharing code or dealing with many projects. So I recommend nix.

**Comment by lecopivo** [comment]
Sounds good, I should give it a try at some point. I'm happy to merge your changes, not sure though if I will be able to maintain them as I do not know nix and don't know when I will find the time to lean it.

**Comment by lecopivo** [comment]
Ahh I merged it, but then I have tried `lake build` and it does not work anymore. So a revert it. How do I reopen this pull request? Or just make a new one. Can you please make sure that `lake build` still workds?

**Comment by Anderssorby** [comment]
Just a sec

**Comment by Anderssorby** [comment]
@lecopivo  I think it should be enough to set `srcDir := "src"` to make it work. Turns out I had to do some fixes to make lake run on NixOS again so haven't tested yet.
https://github.com/yatima-inc/lake/

**Pull request merged**
